-- 创建应用数据库
CREATE DATABASE IF NOT EXISTS \$MYSQL_DATABASE;

-- 创建用户并授权
CREATE USER IF NOT EXISTS '\$MYSQL_USER'@'%' IDENTIFIED BY '\$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON \$MYSQL_DATABASE.* TO '\$MYSQL_USER'@'%';
FLUSH PRIVILEGES;